### PR TITLE
Added action to get and set commands towards the Grohe devices

### PR DESCRIPTION
**Pull request by Flo-Schilli**
#47

### CODE REVIEW

**Comment by daxyorg** [comment]
Hi @Flo-Schilli ! I try v0.20.2 [[develop](https://github.com/Flo-Schilli/homeassistant-grohe_sense/tree/develop)] version.
These two indicators doesn't work on Guard (v 02.06 ;) )


Screenshot 2024-12-17 at 19 26 10

Maybe this is `Water consumption` indicator

Screenshot 2024-12-17 at 19 26 33

Cannot find log :(

**Comment by Flo-Schilli** [comment]
Consumption today changed to water consumption how it is/was named in v.0.10.2

The PM: Runtime you in gen shouldn't see - I think - despite you also now do have a newer version of the Guard 😊 are you also seeing the other PM sensors?

Can you please call the Grohe Sense: Get appliance pressure measurement in the dev-tools if you also get something returned there 😊

**Comment by Flo-Schilli** [comment]
But I guess you're not seeing them (with unavailable) because they are not exposed for your Guard version from the integration :smile:

**Comment by daxyorg** [comment]
**Grohe Sense: Get Appliance data**

```
appliance_id: *SENSE sensor*
type: 101
data:
  group_by: day
  measurement:
    - date: "2024-12-17"
      temperature: 24.33
      humidity: 33
```


```
appliance_id: *GUARD*
type: 103
data:
  group_by: hour
  measurement:
    - date: "2024-12-17 19:00:00"
      flowrate: 0
      pressure: 3.7
      temperature_guard: 16.33
      min_pressure: 3.6
      max_pressure: 3.8
      median_pressure: 3.7
      q1_pressure: 3.65
      q3_pressure: 3.75
    - date: "2024-12-17 18:00:00"
      flowrate: 0
      pressure: 3.8
      temperature_guard: 15.88
      min_pressure: 3.7
      max_pressure: 3.9
      median_pressure: 3.8
      q1_pressure: 3.77
      q3_pressure: 3.83
  withdrawals:
    - date: "2024-12-17 18:00:00"
      waterconsumption: 9.1
      hotwater_share: 0
      water_cost: 0
      energy_cost: 0
      max_flowrate: 12.7
```

**Grohe Sense: Get Appliance notifications**

No data for the sensors.

```
notifications:
  - appliance_id: *GUARD*
    id: xxxx
    category: 30
    is_read: true
    timestamp: "2024-12-15T19:54:27.000+02:00"
    type: 430
    threshold_quantity: "no"
    threshold_type: "no"
  - appliance_id: xxxx
    id: xxxx
    category: 30
    is_read: true
    timestamp: "2024-12-15T19:15:50.000+02:00"
    type: 430
    threshold_quantity: "no"
    threshold_type: "no"
```




This is only view, about PM:

Screenshot 2024-12-17 at 19 50 36


If you need more data, just write me :)

**Comment by daxyorg** [comment]
> But I guess you're not seeing them (with unavailable) because they are not exposed for your Guard version from the integration 😄

Correct me if I'm wrong, but when it comes to pressure, - minimum, maximum and median, I think I have them.

```
      min_pressure: 3.7
      max_pressure: 3.9
      median_pressure: 3.8
```

**Comment by daxyorg** [comment]
Maybe here it's the answer?:

Supported_futures: 0


Screenshot 2024-12-17 at 20 37 59

**Comment by Flo-Schilli** [comment]
Yeah but the PM is an old sensor for the pressure measurement the Sense guard is doing at night and which should not be exposed anymore to your guard version 😊 and you can just remove it or reset up the integration 😊

**Pull request merged**
